import { StyleSheet } from 'react-native'

export default StyleSheet.create({
    container: {
        backgroundColor: "#F9F3EE",
        flex: 1,
    },
    SearchBar: {
        height: 80,
        backgroundColor: "#FFA939",
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
    },
    LocationBar: {
        height: 45,
    },
    ButtonBuy: {
        width: "50%",
        borderRadius: 30,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        paddingTop: 10,
        paddingBottom: 10,
        paddingRight: 10,
        paddingLeft: 10,
        marginBottom: 10,
        borderColor: "rgba(255, 255, 255, 0.5)",
        borderWidth: 2,
        borderStyle: "solid",
        backgroundColor: "#009CC6",
        marginTop: 20,
        marginLeft: 10,
        marginRight: 10,
    },
    ButtonAdvance: {
        width: "95%",
        borderRadius: 30,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        paddingTop: 15,
        paddingBottom: 15,
        paddingRight: 50,
        paddingLeft: 50,
        marginBottom: 10,
        borderColor: "rgba(255, 255, 255, 0.5)",
        borderWidth: 2,
        borderStyle: "solid",
        backgroundColor: "#009CC6",
        marginTop: 20,
        marginLeft: 10,
        marginRight: 10,
    },
    Text: {
        fontSize: 18,
        color: "white",
    },
    TextTotal: {
        fontSize: 20,
        color: "white",
        marginLeft: 10,
    },
})